title: Guneykan Ozgul
#url: "https://guneykan.github.io"
#baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://guneykan.github.io"
footer_text: "https://guneykan.github.io/"

sass:
    style: compressed
    sass_dir: _sass

